# Generated by Django 4.2.5 on 2023-10-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('service_required', models.CharField(blank=True, choices=[('dentalfillings', 'Dental Fillings'), ('root_canal_treatment', 'Root Canal Treatment'), ('dental_crown', 'Dental Crown'), ('wisdom_tooth_removal', 'Wisdom Tooth Removal'), ('aligners/invisible_braces', 'Aligners/Invisible Braces'), ('dental_braces', 'Dental Braces'), ('dental_implants', 'Dental Implants'), ('smile_makeover', 'Smile Makeover'), ('denture', 'Denture'), ('teeth_whitening', 'Teeth Whitening'), ('mouth_ulcers', 'Mouth Ulcers'), ('kids_dentistry', 'Kids Dentistry'), ('diabetic_dental_care', 'Diabetic Dental Care'), ('preventive_dentistry', 'Preventive Dentistry'), ('others', 'Others')], max_length=40, null=True)),
                ('location', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Appointment Request',
                'verbose_name_plural': 'Appointment Requests',
            },
        ),
        migrations.CreateModel(
            name='Upcoming_Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=15)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Upcoming Appointment',
                'verbose_name_plural': 'Upcoming Appointments',
            },
        ),
    ]
